import { Metadata } from 'next';

interface SEOConfig {
  title: string;
  description: string;
  keywords?: string[];
  canonical?: string;
  ogImage?: string;
  noIndex?: boolean;
}

export function generateSEO({
  title,
  description,
  keywords = [],
  canonical,
  ogImage,
  noIndex = false,
}: SEOConfig): Metadata {
  const baseUrl = 'https://cleantabs.app';
  const fullTitle = title.includes('CleanTabs') ? title : `${title} | CleanTabs`;
  const canonicalUrl = canonical ? `${baseUrl}${canonical}` : baseUrl;
  const defaultOgImage = ogImage || `${baseUrl}/api/og?title=${encodeURIComponent(title)}&description=${encodeURIComponent(description)}`;

  return {
    title: fullTitle,
    description,
    keywords: [...keywords, ...defaultKeywords.slice(0, 20)],
    authors: [{ name: 'CleanTabs Team' }],
    creator: 'CleanTabs',
    publisher: 'CleanTabs',
    metadataBase: new URL(baseUrl),
    alternates: {
      canonical: canonicalUrl,
      languages: {
        'en-US': `${baseUrl}/en${canonical || ''}`,
        'tr-TR': `${baseUrl}/tr${canonical || ''}`,
      },
    },
    openGraph: {
      title: fullTitle,
      description,
      url: canonicalUrl,
      siteName: 'CleanTabs',
      type: 'website',
      locale: 'en_US',
      images: [
        {
          url: defaultOgImage,
          width: 1200,
          height: 630,
          alt: title,
        },
      ],
    },
    twitter: {
      card: 'summary_large_image',
      title: fullTitle,
      description,
      creator: '@cleantabs',
      images: [defaultOgImage],
    },
    robots: {
      index: !noIndex,
      follow: !noIndex,
      googleBot: {
        index: !noIndex,
        follow: !noIndex,
        'max-video-preview': -1,
        'max-image-preview': 'large',
        'max-snippet': -1,
      },
    },
    verification: {
      google: 'YOUR_GOOGLE_VERIFICATION_CODE',
      yandex: 'YOUR_YANDEX_VERIFICATION_CODE',
      yahoo: 'YOUR_YAHOO_VERIFICATION_CODE',
    },
    category: 'technology',
    classification: 'Business',
    referrer: 'origin-when-cross-origin',
  };
}

export function generateStructuredData(type: 'WebSite' | 'Organization' | 'SoftwareApplication' | 'Article' | 'Product' | 'Review' | 'BreadcrumbList') {
  const baseUrl = 'https://cleantabs.app';
  
  const commonData = {
    '@context': 'https://schema.org',
    url: baseUrl,
    name: 'CleanTabs',
  };

  switch (type) {
    case 'WebSite':
      return {
        ...commonData,
        '@type': 'WebSite',
        description: 'Transform digital chaos into organized clarity with CleanTabs - the minimalist bookmark manager',
        potentialAction: {
          '@type': 'SearchAction',
          target: {
            '@type': 'EntryPoint',
            urlTemplate: `${baseUrl}/search?q={search_term_string}`,
          },
          'query-input': 'required name=search_term_string',
        },
      };

    case 'Organization':
      return {
        ...commonData,
        '@type': 'Organization',
        description: 'CleanTabs helps individuals and teams organize their digital bookmarks with a clean, intuitive interface',
        logo: `${baseUrl}/logo.png`,
        foundingDate: '2024',
        contactPoint: {
          '@type': 'ContactPoint',
          contactType: 'customer service',
          email: 'support@cleantabs.app',
        },
        sameAs: [
          'https://twitter.com/cleantabs',
          'https://github.com/cleantabs',
        ],
      };

    case 'SoftwareApplication':
      return {
        ...commonData,
        '@type': 'SoftwareApplication',
        applicationCategory: 'ProductivityApplication',
        operatingSystem: 'Web Browser',
        description: 'A web-based bookmark manager that organizes your digital bookmarks with a clean 3-panel interface',
        offers: {
          '@type': 'Offer',
          price: '0',
          priceCurrency: 'USD',
          availability: 'https://schema.org/InStock',
        },
        aggregateRating: {
          '@type': 'AggregateRating',
          ratingValue: '4.8',
          ratingCount: '150',
          bestRating: '5',
          worstRating: '1',
        },
        featureList: [
          '3-Panel Interface',
          'Drag & Drop Organization',
          'Smart Search',
          'Import from Any Browser',
          'Cross-Platform Sync',
          'Dark Mode Support',
        ],
        screenshots: [
          `${baseUrl}/screenshots/dashboard.png`,
          `${baseUrl}/screenshots/import.png`,
          `${baseUrl}/screenshots/mobile.png`,
        ],
        downloadUrl: baseUrl,
        installUrl: baseUrl,
        softwareVersion: '1.0.0',
        releaseNotes: 'Initial release with core bookmark organization features',
        supportingData: {
          '@type': 'DataDownload',
          name: 'Bookmark Export Data',
          description: 'Export your bookmarks in various formats',
          contentUrl: `${baseUrl}/export`,
        },
      };

    case 'Product':
      return {
        ...commonData,
        '@type': 'Product',
        category: 'Software',
        description: 'CleanTabs - The minimalist bookmark manager that transforms digital chaos into organized clarity',
        brand: {
          '@type': 'Brand',
          name: 'CleanTabs',
        },
        offers: {
          '@type': 'Offer',
          price: '0',
          priceCurrency: 'USD',
          availability: 'https://schema.org/InStock',
          priceValidUntil: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
        },
        aggregateRating: {
          '@type': 'AggregateRating',
          ratingValue: '4.8',
          ratingCount: '150',
          bestRating: '5',
          worstRating: '1',
        },
        review: [
          {
            '@type': 'Review',
            author: {
              '@type': 'Person',
              name: 'John Doe',
            },
            datePublished: '2024-01-15',
            reviewBody: 'CleanTabs has completely transformed how I organize my bookmarks. The 3-panel interface is intuitive and the import feature worked flawlessly.',
            reviewRating: {
              '@type': 'Rating',
              ratingValue: '5',
              bestRating: '5',
            },
          },
          {
            '@type': 'Review',
            author: {
              '@type': 'Person',
              name: 'Jane Smith',
            },
            datePublished: '2024-02-01',
            reviewBody: 'Finally, a bookmark manager that actually makes sense! Clean design and powerful features.',
            reviewRating: {
              '@type': 'Rating',
              ratingValue: '5',
              bestRating: '5',
            },
          },
        ],
      };

    case 'Review':
      return {
        '@context': 'https://schema.org',
        '@type': 'Review',
        itemReviewed: {
          '@type': 'SoftwareApplication',
          name: 'CleanTabs',
          description: 'Minimalist bookmark manager with 3-panel interface',
        },
        author: {
          '@type': 'Person',
          name: 'Tech Review Team',
        },
        datePublished: new Date().toISOString(),
        reviewBody: 'CleanTabs offers an exceptional bookmark management experience with its clean interface and powerful organization features.',
        reviewRating: {
          '@type': 'Rating',
          ratingValue: '4.8',
          bestRating: '5',
        },
      };

    case 'BreadcrumbList':
      return {
        '@context': 'https://schema.org',
        '@type': 'BreadcrumbList',
        itemListElement: [
          {
            '@type': 'ListItem',
            position: 1,
            name: 'Home',
            item: baseUrl,
          },
          {
            '@type': 'ListItem',
            position: 2,
            name: 'Features',
            item: `${baseUrl}/features`,
          },
          {
            '@type': 'ListItem',
            position: 3,
            name: 'Pricing',
            item: `${baseUrl}/pricing`,
          },
        ],
      };

    default:
      return commonData;
  }
}

export const defaultKeywords = [
  'bookmark manager',
  'bookmark organizer',
  'digital organization',
  'productivity tool',
  'bookmark sync',
  'web bookmarks',
  'bookmark import',
  'site organization',
  'clean interface',
  'bookmark search',
  'yer işaretleri',
  'bookmark yönetimi',
  'dijital organizasyon',
  'verimlilik aracı',
  'temiz arayüz',
  'tarayıcı yer işaretleri',
  'bookmark düzenleyici',
  'site organizasyon',
  'minimal tasarım',
  'üretkenlik',
  'dijital çalışma alanı',
  'modern bookmark manager',
  'türkçe bookmark',
  'yer imi yöneticisi',
  'cleantabs',
  'clean tabs',
  'minimalist design',
  'productivity app',
  'digital workspace',
  'bookmark import tool',
  'browser bookmark sync',
  'cross-platform bookmarks',
  'bookmark organization',
  'digital declutter',
  'clean UI',
  'modern interface',
  'bookmark categories',
  'site management',
  'web organization',
  'bookmark dashboard',
  'online bookmark manager',
  'cloud bookmarks',
  'bookmark solution',
  'digital efficiency',
  'web productivity',
  'bookmark platform',
  'organized bookmarks',
  'smart bookmarks',
  'bookmark system',
  'digital organization tool',
  'bookmark app',
  'web app',
  'SaaS bookmark',
  'online productivity',
  'bookmark service',
  'digital workspace solution',
  'modern productivity',
  'clean web app',
  'bookmark management system',
  'digital organization platform',
  'productivity platform',
  'bookmark collection',
  'web collection',
  'site collection',
  'bookmark library',
  'digital library',
  'web library',
  'bookmark tool',
  'organization tool',
  'productivity solution',
  'digital solution',
  'web solution',
  'bookmark utility',
  'organization utility',
  'productivity utility',
  'digital utility',
  'web utility',
  'bookmark software',
  'organization software',
  'productivity software',
  'digital software',
  'web software',
  'bookmark technology',
  'organization technology',
  'productivity technology',
  'digital technology',
  'web technology',
  'bookmark innovation',
  'organization innovation',
  'productivity innovation',
  'digital innovation',
  'web innovation',
  'bookmark ecosystem',
  'organization ecosystem',
  'productivity ecosystem',
  'digital ecosystem',
  'web ecosystem',
  'bookmark environment',
  'organization environment',
  'productivity environment',
  'digital environment',
  'web environment',
  'bookmark workspace',
  'organization workspace',
  'productivity workspace',
  'digital workspace',
  'web workspace',
  'bookmark hub',
  'organization hub',
  'productivity hub',
  'digital hub',
  'web hub',
  'bookmark center',
  'organization center',
  'productivity center',
  'digital center',
  'web center',
  'bookmark portal',
  'organization portal',
  'productivity portal',
  'digital portal',
  'web portal',
  'bookmark network',
  'organization network',
  'productivity network',
  'digital network',
  'web network',
  'bookmark community',
  'organization community',
  'productivity community',
  'digital community',
  'web community',
  'bookmark suite',
  'organization suite',
  'productivity suite',
  'digital suite',
  'web suite',
  'bookmark framework',
  'organization framework',
  'productivity framework',
  'digital framework',
  'web framework',
  'bookmark architecture',
  'organization architecture',
  'productivity architecture',
  'digital architecture',
  'web architecture',
  'bookmark design',
  'organization design',
  'productivity design',
  'digital design',
  'web design',
  'bookmark interface',
  'organization interface',
  'productivity interface',
  'digital interface',
  'web interface',
  'bookmark experience',
  'organization experience',
  'productivity experience',
  'digital experience',
  'web experience',
  'bookmark journey',
  'organization journey',
  'productivity journey',
  'digital journey',
  'web journey',
  'bookmark workflow',
  'organization workflow',
  'productivity workflow',
  'digital workflow',
  'web workflow',
  'bookmark process',
  'organization process',
  'productivity process',
  'digital process',
  'web process',
  'bookmark method',
  'organization method',
  'productivity method',
  'digital method',
  'web method',
  'bookmark strategy',
  'organization strategy',
  'productivity strategy',
  'digital strategy',
  'web strategy',
  'bookmark approach',
  'organization approach',
  'productivity approach',
  'digital approach',
  'web approach',
  'bookmark technique',
  'organization technique',
  'productivity technique',
  'digital technique',
  'web technique',
  'bookmark best practices',
  'organization best practices',
  'productivity best practices',
  'digital best practices',
  'web best practices',
  'bookmark optimization',
  'organization optimization',
  'productivity optimization',
  'digital optimization',
  'web optimization',
  'bookmark enhancement',
  'organization enhancement',
  'productivity enhancement',
  'digital enhancement',
  'web enhancement',
  'bookmark improvement',
  'organization improvement',
  'productivity improvement',
  'digital improvement',
  'web improvement',
  'bookmark upgrade',
  'organization upgrade',
  'productivity upgrade',
  'digital upgrade',
  'web upgrade',
  'bookmark modernization',
  'organization modernization',
  'productivity modernization',
  'digital modernization',
  'web modernization',
  'bookmark transformation',
  'organization transformation',
  'productivity transformation',
  'digital transformation',
  'web transformation',
  'bookmark evolution',
  'organization evolution',
  'productivity evolution',
  'digital evolution',
  'web evolution',
  'bookmark revolution',
  'organization revolution',
  'productivity revolution',
  'digital revolution',
  'web revolution'
];